import { StyleSheet } from 'react-native';
import { voiceAssistantPalette } from './tokens';

export const voiceAssistantListThemeClass = {
  safeArea: 'flex-1 bg-white',
  screen: 'flex-1 bg-white',
  header: 'flex-row items-center justify-between border-b border-black/5 bg-white px-4 py-3',
  headerSide: 'w-16 flex-row items-center gap-3',
  headerCenter: 'flex-1 items-center',
  headerTitle: 'text-[18px] font-semibold text-slate-900',
  headerAction: 'h-10 w-10 items-center justify-center rounded-full',
  featuredCard: 'mx-4 mt-3 flex-row items-center rounded-[24px] border border-slate-100 bg-white px-4 py-4',
  featuredAvatarOuter: 'h-14 w-14 items-center justify-center rounded-full border border-slate-100 bg-white',
  featuredAvatarInner: 'h-11 w-11 items-center justify-center rounded-full bg-sky-100',
  featuredAvatarText: 'text-[18px] font-semibold text-sky-700',
  featuredBody: 'ml-3 flex-1',
  featuredTitleRow: 'flex-row items-center',
  featuredTitle: 'text-[17px] font-medium text-slate-900',
  featuredBadge: 'ml-2 rounded-md border border-blue-100 bg-blue-50 px-2 py-1',
  featuredBadgeText: 'text-[10px] font-semibold text-blue-500',
  featuredSubtitle: 'mt-1 text-[14px] text-slate-400',
  featuredVoiceButton: 'ml-3 h-11 w-11 items-center justify-center rounded-full bg-slate-900',
  sectionLabel: 'px-4 pb-2 pt-4 text-[12px] font-semibold uppercase tracking-[1.4px] text-slate-400',
  listRow: 'flex-row items-center border-b border-black/5 bg-white px-4 py-4',
  listAvatarOuter: 'h-14 w-14 items-center justify-center rounded-full',
  listAvatarInner: 'h-10 w-10 items-center justify-center rounded-full',
  listAvatarText: 'text-[17px] font-semibold text-slate-700',
  listBody: 'ml-3 flex-1',
  listTitle: 'text-[17px] font-medium text-slate-900',
  listPreview: 'mt-1 text-[14px] leading-5 text-slate-400',
  listMeta: 'ml-3 text-[12px] font-medium text-slate-300',
  emptyState: 'mx-4 mt-6 rounded-[24px] border border-slate-100 bg-slate-50 px-5 py-6',
  emptyStateTitle: 'text-[16px] font-medium text-slate-900',
  emptyStateBody: 'mt-2 text-[14px] leading-6 text-slate-500',
  bottomTabs: 'border-t border-slate-100 bg-white px-10 pb-6 pt-2',
  bottomTabsRow: 'flex-row items-center justify-between',
  tabItem: 'items-center justify-center',
  tabLabel: 'mt-1 text-[11px] text-slate-400',
  tabLabelActive: 'mt-1 text-[11px] font-semibold text-black',
  tabBadge: 'absolute -right-2 -top-1 min-w-[18px] rounded-full bg-red-500 px-1.5 py-0.5',
  tabBadgeText: 'text-[10px] font-bold text-white',
} as const;

export const voiceAssistantConversationThemeClass = {
  safeArea: 'flex-1 bg-[#FBFCFE]',
  screen: 'flex-1 bg-[#FBFCFE]',
  header: 'border-b border-black/5 bg-white/90 px-4 pb-3 pt-2',
  headerRow: 'flex-row items-center justify-between',
  headerButton: 'h-10 w-10 items-center justify-center rounded-full',
  headerCenter: 'flex-1 items-center px-3',
  headerTitle: 'text-[17px] font-medium text-slate-900',
  headerSubtext: 'mt-0.5 text-[11px] text-slate-400',
  modeSwitchRow: 'mt-3 flex-row items-center gap-2',
  modeChip: 'flex-row items-center rounded-full border border-slate-200 bg-white px-4 py-2.5',
  modeChipActive: 'flex-row items-center rounded-full bg-slate-900 px-4 py-2.5',
  modeChipText: 'ml-1.5 text-[14px] text-slate-600',
  modeChipActiveText: 'ml-1.5 text-[14px] font-medium text-white',
  messageArea: 'flex-1 px-4 pt-4',
  emptyBubble: 'rounded-[20px] rounded-bl-[6px] bg-[#F4F5F7] px-4 py-3 self-start max-w-[82%]',
  emptyBubbleText: 'text-[16px] leading-6 text-slate-800',
  composerMetaRow: 'flex-row items-center justify-between border-t border-black/5 bg-white/90 px-4 pb-2 pt-3',
  composerMetaText: 'max-w-[72%] text-[12px] leading-5 text-slate-400',
  connectionTextButton: 'rounded-full bg-slate-100 px-3 py-2',
  connectionTextButtonText: 'text-[12px] font-medium text-slate-600',
  composerDock: 'flex-row items-center bg-white/90 px-4 pb-8 pt-3',
  iconButton: 'h-11 w-11 items-center justify-center rounded-full',
  iconButtonSoft: 'h-11 w-11 items-center justify-center rounded-full bg-slate-100',
  inputShell: 'mx-3 flex-1 flex-row items-center rounded-full bg-slate-100/70 px-4 py-2.5',
  inputField: 'flex-1 text-[16px] text-slate-900',
  inputPlaceholder: 'text-slate-400',
  primaryComposerAction: 'ml-2 h-11 min-w-[44px] items-center justify-center rounded-full bg-slate-900 px-4',
  primaryComposerActionText: 'text-[14px] font-semibold text-white',
  floatingVoiceButton: 'h-11 w-11 items-center justify-center rounded-full bg-blue-500',
} as const;

export const voiceAssistantBubbleThemeClass = {
  assistantBubble: 'mb-5 self-start max-w-[88%] rounded-[20px] rounded-bl-[6px] bg-[#F4F5F7] px-4 py-3',
  assistantCardWrap: 'mb-5 self-start w-[86%] rounded-[24px] bg-[#F7F8FA] p-1.5',
  assistantCardPanel: 'rounded-[18px] border border-black/5 bg-white px-5 py-4',
  assistantCardText: 'text-[16px] leading-[26px] text-slate-800',
  assistantActions: 'mt-2 flex-row items-center justify-between px-2 pb-1',
  assistantActionLeft: 'flex-row items-center gap-2',
  assistantActionButton: 'h-9 w-9 items-center justify-center rounded-[10px] bg-blue-50',
  assistantRetryButton: 'h-9 w-9 items-center justify-center rounded-full',
  assistantText: 'text-[16px] leading-6 text-slate-800',
  narrationText: 'text-[16px] leading-6 text-slate-400',
  userBubble: 'mb-5 self-end max-w-[74%] rounded-[20px] rounded-br-[6px] bg-[#0A7CFF] px-4 py-3',
  userText: 'text-[16px] leading-6 text-white',
} as const;

export const voiceAssistantVoiceThemeClass = {
  safeArea: 'flex-1 bg-[#FBF6FF]',
  screen: 'flex-1 overflow-hidden bg-[#FBF6FF]',
  blobBase: 'absolute rounded-full',
  header: 'flex-row items-center justify-between px-4 pb-4 pt-3',
  headerButton: 'h-10 w-10 items-center justify-center rounded-full bg-white/20',
  headerCenter: 'flex-1 flex-row items-center justify-center gap-2',
  headerTitle: 'text-[18px] font-medium text-slate-800',
  textModeButton: 'h-10 w-10 items-center justify-center rounded-full bg-white/35',
  body: 'flex-1 items-center justify-center px-6',
  avatarOuter: 'h-64 w-64 items-center justify-center rounded-full border-[10px] border-white/40 bg-white/10',
  avatarInner: 'h-60 w-60 items-center justify-center rounded-full border-4 border-white bg-sky-100',
  avatarCore: 'h-52 w-52 items-center justify-center rounded-full bg-white/80',
  avatarTitle: 'text-[56px] font-black tracking-[-2px] text-slate-700',
  avatarSubtitle: 'mt-2 text-[15px] text-slate-500',
  statusDots: 'mt-12 flex-row items-center gap-2',
  statusDot: 'h-3 w-3 rounded-full bg-slate-500/70',
  statusText: 'mt-5 text-[18px] tracking-[3px] text-slate-500',
  metaText: 'mt-3 text-[14px] text-slate-400',
  transcriptCard: 'mt-10 w-full rounded-[24px] bg-white/55 px-5 py-4',
  transcriptLabel: 'text-[12px] uppercase tracking-[1.6px] text-slate-400',
  transcriptTitle: 'mt-2 text-[16px] font-medium text-slate-800',
  transcriptBody: 'mt-2 text-[14px] leading-6 text-slate-500',
  footer: 'px-6 pb-12 pt-4',
  controlsRow: 'flex-row items-center justify-between px-2',
  secondaryControl: 'h-16 w-16 items-center justify-center rounded-full bg-white/45',
  dangerControl: 'h-16 w-16 items-center justify-center rounded-full bg-red-200',
  primaryControl: 'h-16 w-16 items-center justify-center rounded-full bg-white/60',
  controlCaption: 'mt-4 text-center text-[14px] text-slate-500',
  attribution: 'mt-8 text-center text-[14px] text-slate-400',
} as const;

export const voiceAssistantThemeStyle = StyleSheet.create({
  listFeaturedShadow: {
    shadowColor: voiceAssistantPalette.shadowWarm,
    shadowOpacity: 1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 3,
  },
  whiteCardShadow: {
    shadowColor: voiceAssistantPalette.shadowWarm,
    shadowOpacity: 1,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  assistantActionShadow: {
    shadowColor: voiceAssistantPalette.shadowWarm,
    shadowOpacity: 0.8,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  voiceAvatarShadow: {
    shadowColor: voiceAssistantPalette.shadowVoice,
    shadowOpacity: 1,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 5,
  },
  voiceTranscriptShadow: {
    shadowColor: voiceAssistantPalette.shadowVoice,
    shadowOpacity: 0.9,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  listScrollContent: {
    paddingBottom: 18,
  },
  conversationScrollContent: {
    paddingBottom: 18,
  },
  quickChipScrollContent: {
    paddingRight: 16,
  },
});
