import { StyleSheet } from 'react-native';
import { voiceAssistantPalette } from './tokens';

export const voiceAssistantListThemeClass = {
  safeArea: 'flex-1 bg-white',
  screen: 'flex-1 bg-white',
  header: 'flex-row items-center justify-between border-b border-black/5 bg-white px-4 py-3',
  headerSide: 'w-16 flex-row items-center gap-3',
  headerCenter: 'flex-1 items-center',
  headerTitle: 'text-[18px] font-semibold text-slate-900',
  headerAction: 'h-10 w-10 items-center justify-center rounded-full',
  featuredCard: 'mx-4 mt-3 flex-row items-center rounded-[24px] border border-slate-100 bg-white px-4 py-4',
  featuredAvatarOuter: 'h-14 w-14 items-center justify-center rounded-full border border-slate-100 bg-white',
  featuredAvatarInner: 'h-11 w-11 items-center justify-center rounded-full bg-sky-100',
  featuredAvatarText: 'text-[18px] font-semibold text-sky-700',
  featuredBody: 'ml-3 flex-1',
  featuredTitleRow: 'flex-row items-center',
  featuredTitle: 'text-[17px] font-medium text-slate-900',
  featuredBadge: 'ml-2 rounded-md border border-blue-100 bg-blue-50 px-2 py-1',
  featuredBadgeText: 'text-[10px] font-semibold text-blue-500',
  featuredSubtitle: 'mt-1 text-[14px] text-slate-400',
  featuredVoiceButton: 'ml-3 h-11 w-11 items-center justify-center rounded-full bg-slate-900',
  sectionLabel: 'px-4 pb-2 pt-4 text-[12px] font-semibold uppercase tracking-[1.4px] text-slate-400',
  listRow: 'flex-row items-center border-b border-black/5 bg-white px-4 py-4',
  listAvatarOuter: 'h-14 w-14 items-center justify-center rounded-full',
  listAvatarInner: 'h-10 w-10 items-center justify-center rounded-full',
  listAvatarText: 'text-[17px] font-semibold text-slate-700',
  listBody: 'ml-3 flex-1',
  listTitle: 'text-[17px] font-medium text-slate-900',
  listPreview: 'mt-1 text-[14px] leading-5 text-slate-400',
  listMeta: 'ml-3 text-[12px] font-medium text-slate-300',
  emptyState: 'mx-4 mt-6 rounded-[24px] border border-slate-100 bg-slate-50 px-5 py-6',
  emptyStateTitle: 'text-[16px] font-medium text-slate-900',
  emptyStateBody: 'mt-2 text-[14px] leading-6 text-slate-500',
  bottomTabs: 'border-t border-slate-100 bg-white px-10 pb-6 pt-2',
  bottomTabsRow: 'flex-row items-center justify-between',
  tabItem: 'items-center justify-center',
  tabLabel: 'mt-1 text-[11px] text-slate-400',
  tabLabelActive: 'mt-1 text-[11px] font-semibold text-black',
  tabBadge: 'absolute -right-2 -top-1 min-w-[18px] rounded-full bg-red-500 px-1.5 py-0.5',
  tabBadgeText: 'text-[10px] font-bold text-white',
} as const;

export const voiceAssistantConversationThemeClass = {
  safeArea: 'flex-1 bg-[#FBFCFE]',
  screen: 'flex-1 bg-[#FBFCFE]',
  header: 'border-b border-black/5 bg-white/90 px-4 pb-3 pt-2',
  headerRow: 'flex-row items-center justify-between',
  headerButton: 'h-10 w-10 items-center justify-center rounded-full',
  headerCenter: 'flex-1 items-center px-3',
  headerTitle: 'text-[17px] font-medium text-slate-900',
  headerSubtext: 'mt-0.5 text-[11px] text-slate-400',
  messageArea: 'flex-1 px-4 pt-4',
  emptyBubble: 'rounded-[20px] rounded-bl-[6px] bg-[#F4F5F7] px-4 py-3 self-start max-w-[82%]',
  emptyBubbleText: 'text-[16px] leading-6 text-slate-800',
  composerDock: 'flex-row items-center bg-white/90 px-4 pb-8 pt-3',
  iconButton: 'h-11 w-11 items-center justify-center rounded-full',
  iconButtonSoft: 'h-11 w-11 items-center justify-center rounded-full bg-slate-100',
  inputShell: 'mx-3 flex-1 flex-row items-center rounded-full bg-slate-100/70 px-4 py-2.5',
  inputField: 'flex-1 text-[16px] text-slate-900',
  inputPlaceholder: 'text-slate-400',
  primaryComposerAction: 'ml-2 h-11 min-w-[44px] items-center justify-center rounded-full bg-slate-900 px-4',
  primaryComposerActionText: 'text-[14px] font-semibold text-white',
  floatingVoiceButton: 'h-11 w-11 items-center justify-center rounded-full bg-blue-500',
  drawerBackdrop: 'absolute inset-0 bg-slate-900/25',
  drawerPanel: 'absolute inset-y-0 left-0 w-[86%] max-w-[340px] border-r border-black/5 bg-white px-4 pb-6 pt-3',
  drawerHeader: 'flex-row items-center justify-between pb-3',
  drawerTitle: 'text-[18px] font-semibold text-slate-900',
  drawerSearchWrap: 'mt-2 flex-row items-center rounded-full bg-slate-100 px-4 py-3',
  drawerSearchInput: 'ml-2 flex-1 text-[15px] text-slate-900',
  drawerActionRow: 'mt-4 flex-row items-center gap-3',
  drawerPrimaryAction: 'rounded-full bg-slate-900 px-4 py-3',
  drawerPrimaryActionText: 'text-[14px] font-semibold text-white',
  drawerGhostAction: 'rounded-full border border-slate-200 bg-white px-4 py-3',
  drawerGhostActionText: 'text-[14px] font-medium text-slate-600',
  drawerSectionLabel: 'pb-2 pt-6 text-[12px] font-semibold uppercase tracking-[1.4px] text-slate-400',
  drawerConversationRow: 'flex-row items-center border-b border-black/5 py-4',
  drawerConversationBody: 'ml-3 flex-1',
  drawerConversationTitle: 'text-[16px] font-medium text-slate-900',
  drawerConversationPreview: 'mt-1 text-[13px] leading-5 text-slate-400',
  drawerConversationMeta: 'text-[12px] text-slate-300',
  drawerConversationActiveBadge: 'mt-1 rounded-full bg-slate-900 px-2 py-1',
  drawerConversationActiveBadgeText: 'text-[10px] font-semibold text-white',
  drawerFooter: 'mt-auto border-t border-black/5 pt-4',
  drawerFooterButton: 'self-start rounded-full bg-slate-100 px-3 py-2',
  drawerFooterButtonText: 'text-[12px] font-medium text-slate-600',
} as const;

export const voiceAssistantBubbleThemeClass = {
  assistantBubble: 'mb-5 self-start max-w-[88%] rounded-[20px] rounded-bl-[6px] bg-[#F4F5F7] px-4 py-3',
  assistantCardWrap: 'mb-5 self-start w-[86%] rounded-[24px] bg-[#F7F8FA] p-1.5',
  assistantCardPanel: 'rounded-[18px] border border-black/5 bg-white px-5 py-4',
  assistantCardText: 'text-[16px] leading-[26px] text-slate-800',
  assistantActions: 'mt-2 flex-row items-center justify-between px-2 pb-1',
  assistantActionLeft: 'flex-row items-center gap-2',
  assistantActionButton: 'h-9 w-9 items-center justify-center rounded-[10px] bg-blue-50',
  assistantRetryButton: 'h-9 w-9 items-center justify-center rounded-full',
  assistantText: 'text-[16px] leading-6 text-slate-800',
  narrationText: 'text-[16px] leading-6 text-slate-400',
  userBubble: 'mb-5 self-end max-w-[74%] rounded-[20px] rounded-br-[6px] bg-[#0A7CFF] px-4 py-3',
  userText: 'text-[16px] leading-6 text-white',
} as const;

export const voiceAssistantVoiceThemeClass = {
  safeArea: 'flex-1 bg-[#FBF6FF]',
  screen: 'flex-1 overflow-hidden bg-[#FBF6FF]',
  blobBase: 'absolute rounded-full',
  header: 'flex-row items-center justify-between px-4 pb-3 pt-2',
  headerButton: 'h-10 w-10 items-center justify-center rounded-full bg-white/18',
  headerCenter: 'flex-1 flex-row items-center justify-center gap-2',
  headerTitle: 'text-[16px] font-medium text-slate-800',
  headerTitleSubtle: 'text-[13px] text-slate-500',
  textModeButton: 'h-10 w-10 items-center justify-center rounded-full bg-white/30',
  textModeButtonLabel: 'text-[18px] font-semibold text-slate-800',
  body: 'flex-1 items-center justify-center px-6',
  dialogueBody: 'flex-1 px-7 pt-10',
  dialogueList: 'flex-1 justify-center gap-5 pb-20',
  dialogueLinePrimary: 'text-[17px] leading-8 text-slate-700',
  dialogueLineSecondary: 'text-[15px] leading-7 text-slate-500',
  avatarOuter: 'h-64 w-64 items-center justify-center rounded-full border-[10px] border-white/40 bg-white/10',
  avatarInner: 'h-60 w-60 items-center justify-center rounded-full border-4 border-white bg-sky-100',
  avatarCore: 'h-52 w-52 items-center justify-center rounded-full bg-white/80',
  avatarTitle: 'text-[56px] font-black tracking-[-2px] text-slate-700',
  avatarSubtitle: 'mt-2 text-[15px] text-slate-500',
  statusDots: 'mt-11 flex-row items-center gap-2',
  statusDot: 'h-3 w-3 rounded-full bg-slate-500/70',
  statusText: 'mt-4 text-[17px] tracking-[1.2px] text-slate-600',
  transcriptStrip: 'mt-8 w-full rounded-[26px] bg-white/40 px-5 py-4',
  transcriptStripLabel: 'text-center text-[12px] uppercase tracking-[1.6px] text-slate-400',
  transcriptStripBody: 'mt-2 text-center text-[15px] leading-6 text-slate-600',
  footer: 'px-7 pb-11 pt-3',
  controlsRow: 'flex-row items-center justify-center gap-5',
  controlShell: 'h-[62px] w-[62px] items-center justify-center rounded-full bg-white/42',
  controlShellMuted: 'h-[62px] w-[62px] items-center justify-center rounded-full bg-white',
  controlShellPlaceholder: 'h-[62px] w-[62px] items-center justify-center rounded-full bg-[#241F31]/10',
  controlShellDanger: 'h-[62px] w-[62px] items-center justify-center rounded-full bg-[#F7E4EC]',
  controlCaption: 'mt-5 text-center text-[14px] text-slate-500',
  debugRow: 'mt-6 items-center justify-center',
  debugButton: 'rounded-full bg-white/45 px-4 py-2',
  debugButtonText: 'text-[12px] font-medium text-slate-600',
  attribution: 'mt-4 text-center text-[13px] text-slate-400',
} as const;

export const voiceAssistantThemeStyle = StyleSheet.create({
  listFeaturedShadow: {
    shadowColor: voiceAssistantPalette.shadowWarm,
    shadowOpacity: 1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 3,
  },
  whiteCardShadow: {
    shadowColor: voiceAssistantPalette.shadowWarm,
    shadowOpacity: 1,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  assistantActionShadow: {
    shadowColor: voiceAssistantPalette.shadowWarm,
    shadowOpacity: 0.8,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  voiceAvatarShadow: {
    shadowColor: voiceAssistantPalette.shadowVoice,
    shadowOpacity: 1,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 5,
  },
  voiceTranscriptShadow: {
    shadowColor: voiceAssistantPalette.shadowVoice,
    shadowOpacity: 0.9,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  listScrollContent: {
    paddingBottom: 18,
  },
  conversationScrollContent: {
    paddingBottom: 18,
  },
  quickChipScrollContent: {
    paddingRight: 16,
  },
});
