import { StyleSheet } from 'react-native';
import { voiceAssistantPalette } from './tokens';

export const voiceAssistantListThemeClass = {
  safeArea: 'flex-1 bg-white',
  screen: 'flex-1 bg-white',
  header: 'flex-row items-center justify-between border-b border-black/5 bg-white px-4 py-3',
  headerSide: 'w-16 flex-row items-center gap-3',
  headerCenter: 'flex-1 items-center',
  headerTitle: 'text-[18px] font-semibold text-slate-900',
  headerAction: 'h-10 w-10 items-center justify-center rounded-full',
  featuredCard: 'mx-4 mt-3 flex-row items-center rounded-[24px] border border-slate-100 bg-white px-4 py-4',
  featuredAvatarOuter: 'h-14 w-14 items-center justify-center rounded-full border border-slate-100 bg-white',
  featuredAvatarInner: 'h-11 w-11 items-center justify-center rounded-full bg-sky-100',
  featuredAvatarText: 'text-[18px] font-semibold text-sky-700',
  featuredBody: 'ml-3 flex-1',
  featuredTitleRow: 'flex-row items-center',
  featuredTitle: 'text-[17px] font-medium text-slate-900',
  featuredBadge: 'ml-2 rounded-md border border-blue-100 bg-blue-50 px-2 py-1',
  featuredBadgeText: 'text-[10px] font-semibold text-blue-500',
  featuredSubtitle: 'mt-1 text-[14px] text-slate-400',
  featuredVoiceButton: 'ml-3 h-11 w-11 items-center justify-center rounded-full bg-slate-900',
  sectionLabel: 'px-4 pb-2 pt-4 text-[12px] font-semibold uppercase tracking-[1.4px] text-slate-400',
  listRow: 'flex-row items-center border-b border-black/5 bg-white px-4 py-4',
  listAvatarOuter: 'h-14 w-14 items-center justify-center rounded-full',
  listAvatarInner: 'h-10 w-10 items-center justify-center rounded-full',
  listAvatarText: 'text-[17px] font-semibold text-slate-700',
  listBody: 'ml-3 flex-1',
  listTitle: 'text-[17px] font-medium text-slate-900',
  listPreview: 'mt-1 text-[14px] leading-5 text-slate-400',
  listMeta: 'ml-3 text-[12px] font-medium text-slate-300',
  emptyState: 'mx-4 mt-6 rounded-[24px] border border-slate-100 bg-slate-50 px-5 py-6',
  emptyStateTitle: 'text-[16px] font-medium text-slate-900',
  emptyStateBody: 'mt-2 text-[14px] leading-6 text-slate-500',
  bottomTabs: 'border-t border-slate-100 bg-white px-10 pb-6 pt-2',
  bottomTabsRow: 'flex-row items-center justify-between',
  tabItem: 'items-center justify-center',
  tabLabel: 'mt-1 text-[11px] text-slate-400',
  tabLabelActive: 'mt-1 text-[11px] font-semibold text-black',
  tabBadge: 'absolute -right-2 -top-1 min-w-[18px] rounded-full bg-red-500 px-1.5 py-0.5',
  tabBadgeText: 'text-[10px] font-bold text-white',
} as const;

export const voiceAssistantConversationThemeClass = {
  safeArea: 'flex-1 bg-[#F9FAFB]',
  screen: 'flex-1 bg-[#F9FAFB]',
  header: 'bg-[#F9FAFB] px-4 pb-2 pt-2',
  headerRow: 'flex-row items-center justify-between',
  headerButton: 'h-9 w-9 items-center justify-center',
  headerCenter: 'flex-1 items-center px-2',
  headerTitleRow: 'flex-row items-center justify-center',
  headerTitle: 'text-[16px] font-medium text-[#111827]',
  headerTitleIcon: 'ml-1 text-[14px] text-slate-400',
  headerSubtext: 'mt-0.5 text-[10px] text-slate-400 opacity-70',
  headerRightActions: 'flex-row items-center',
  messageArea: 'flex-1 px-4 pt-6',
  emptyBubble: 'rounded-3xl bg-[#F6F6F6] px-5 py-4 self-start max-w-[82%]',
  emptyBubbleText: 'text-[15px] leading-6 text-slate-600',
  composerDock: 'bg-[#F9FAFB] px-4 pb-8 pt-3',
  featureChipsScroll: 'mb-3',
  featureChipsContent: 'pr-4',
  featureChip: 'flex-row items-center border border-gray-200 bg-white rounded-xl px-3 py-1.5 mr-2',
  featureChipText: 'ml-1.5 text-[13px] text-slate-700',
  composerContainer: 'flex-row items-center bg-white rounded-2xl px-2 py-1.5 border border-black/5 shadow-sm shadow-black/5',
  iconButton: 'h-11 w-11 items-center justify-center rounded-full',
  iconButtonSoft: 'h-9 w-9 items-center justify-center',
  inputShell: 'flex-1 flex-row items-center bg-transparent py-1',
  inputField: 'flex-1 text-[15px] text-[#111827] px-3',
  inputPlaceholder: 'text-slate-400',
  primaryComposerAction: 'ml-1 h-8 w-14 items-center justify-center rounded-xl bg-[#007AFF]',
  primaryComposerActionText: 'text-[13px] font-medium text-white',
  floatingVoiceButton: 'h-11 w-11 items-center justify-center rounded-full bg-blue-500',
  drawerBackdrop: 'absolute inset-0 bg-black/15',
  drawerPanel: 'absolute inset-y-0 left-0 w-[86%] max-w-[340px] border-r border-black/5 bg-[#FDFDFD] px-4 pb-6 pt-3',
  drawerHeader: 'hidden',
  drawerTitle: 'text-[17px] font-medium text-[#111827]',
  drawerSearchWrap: 'mt-1 flex-row items-center mb-2',
  drawerSearchInner: 'flex-1 flex-row items-center rounded-2xl bg-[#F6F6F6] px-3.5 py-2.5',
  drawerSearchInput: 'ml-2.5 flex-1 text-[15px] text-[#111827]',
  drawerSearchAction: 'ml-3 h-[42px] w-[42px] items-center justify-center rounded-2xl bg-[#F6F6F6]',
  drawerGhostAction: 'rounded-full border border-slate-200 bg-white px-4 py-3',
  drawerGhostActionText: 'text-[14px] font-medium text-slate-600',
  drawerSectionLabel: 'hidden',
  drawerConversationRow: 'flex-row items-center rounded-2xl py-3 px-3 mb-1',
  drawerConversationBody: 'ml-3 flex-1',
  drawerConversationTitle: 'text-[15px] font-medium text-[#111827]',
  drawerConversationPreview: 'hidden',
  drawerConversationMeta: 'text-[12px] text-slate-400 font-normal',
  drawerConversationActiveBadge: 'hidden',
  drawerConversationActiveBadgeText: 'hidden',
  drawerFooter: 'mt-auto border-t border-black/5 pt-3',
  drawerFooterButton: 'self-start rounded-full bg-slate-100 px-3 py-2',
  drawerFooterButtonText: 'text-[12px] font-medium text-slate-600',
} as const;

export const voiceAssistantBubbleThemeClass = {
  assistantBubble: 'mb-6 self-start max-w-[85%] rounded-3xl bg-[#F4F5F6] px-5 py-3.5',
  assistantCardWrap: 'mb-6 self-start w-[88%] rounded-3xl bg-[#F4F5F6]',
  assistantCardPanel: 'px-5 pt-4 pb-3',
  assistantDivider: 'mx-5 h-[1px] bg-black/5',
  assistantCardText: 'text-[16px] leading-[26px] text-[#111827]',
  assistantActions: 'flex-row items-center justify-between px-3 pb-2 pt-1',
  assistantActionLeft: 'flex-row items-center gap-2',
  assistantActionButton: 'h-8 w-8 items-center justify-center rounded-full bg-slate-100/50',
  assistantRetryButton: 'h-8 w-8 items-center justify-center rounded-full bg-slate-100/50',
  assistantText: 'text-[16px] leading-[26px] text-[#111827]',
  narrationText: 'text-[16px] leading-[26px] text-slate-400',
  userBubble: 'mb-6 self-end max-w-[78%] rounded-3xl bg-[#007AFF] px-5 py-3.5',
  userText: 'text-[16px] leading-[24px] text-white',
} as const;

export const voiceAssistantVoiceThemeClass = {
  safeArea: 'flex-1 bg-[#FBF6FF]',
  screen: 'flex-1 overflow-hidden',
  blobBase: 'absolute rounded-full',
  header: 'flex-row items-center justify-between px-4 pb-2 pt-1',
  headerButton: 'h-9 w-9 items-center justify-center rounded-full bg-white/20',
  headerCenter: 'flex-1 flex-row items-center justify-center gap-2',
  headerTitle: 'text-[15px] font-medium text-slate-700',
  headerTitleSubtle: 'text-[13px] text-slate-500',
  textModeButton: 'h-9 w-9 items-center justify-center rounded-full bg-white/34',
  textModeButtonLabel: 'text-[18px] font-semibold text-slate-800',
  body: 'flex-1 items-center justify-center px-6',
  dialogueBody: 'flex-1 px-7 pt-8',
  dialogueList: 'flex-1 justify-center gap-4 pb-16',
  dialogueLinePrimary: 'self-start max-w-[90%] rounded-[20px] rounded-bl-[8px] bg-white/75 px-4 py-3 text-[16px] leading-7 text-slate-700',
  dialogueLineSecondary: 'self-end max-w-[90%] rounded-[20px] rounded-br-[8px] bg-[#161C2D]/85 px-4 py-3 text-[15px] leading-6 text-white',
  avatarOuter: 'h-64 w-64 items-center justify-center rounded-full border-[10px] border-white/40 bg-white/10',
  avatarInner: 'h-60 w-60 items-center justify-center rounded-full border-4 border-white bg-sky-100',
  avatarCore: 'h-52 w-52 items-center justify-center rounded-full bg-white/80',
  avatarTitle: 'text-[56px] font-black tracking-[-2px] text-slate-700',
  avatarSubtitle: 'mt-2 text-[15px] text-slate-500',
  statusDots: 'mt-9 flex-row items-center gap-2',
  statusDot: 'h-2.5 w-2.5 rounded-full bg-slate-500/70',
  statusText: 'mt-4 text-[16px] tracking-[1.1px] text-slate-600',
  transcriptStrip: 'mt-8 w-full rounded-[26px] bg-white/40 px-5 py-4',
  transcriptStripLabel: 'text-center text-[12px] uppercase tracking-[1.6px] text-slate-400',
  transcriptStripBody: 'mt-2 text-center text-[15px] leading-6 text-slate-600',
  footer: 'px-7 pb-9 pt-2',
  controlsRow: 'flex-row items-center justify-center gap-4',
  controlShell: 'h-[58px] w-[58px] items-center justify-center rounded-full bg-white/48',
  controlShellIdle: 'h-[58px] w-[58px] items-center justify-center rounded-full bg-white/62',
  controlShellMuted: 'h-[58px] w-[58px] items-center justify-center rounded-full border border-[#FCA5A5] bg-white/78',
  controlShellSpeaking: 'h-[58px] w-[58px] items-center justify-center rounded-full bg-[#2563EB]',
  controlShellPlaceholder: 'h-[58px] w-[58px] items-center justify-center rounded-full bg-[#1E1B2E]/12',
  controlShellDanger: 'h-[58px] w-[58px] items-center justify-center rounded-full bg-[#FDE7EF]',
  controlCaption: 'mt-5 text-center text-[14px] text-slate-500',
  debugRow: 'mt-6 items-center justify-center',
  debugButton: 'rounded-full bg-white/45 px-4 py-2',
  debugButtonText: 'text-[12px] font-medium text-slate-600',
  attribution: 'mt-3 text-center text-[12px] text-slate-400',
} as const;

export const voiceAssistantThemeStyle = StyleSheet.create({
  listFeaturedShadow: {
    shadowColor: voiceAssistantPalette.shadowWarm,
    shadowOpacity: 1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 3,
  },
  whiteCardShadow: {
    shadowColor: voiceAssistantPalette.shadowWarm,
    shadowOpacity: 1,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  assistantActionShadow: {
    shadowColor: voiceAssistantPalette.shadowWarm,
    shadowOpacity: 0.8,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  voiceAvatarShadow: {
    shadowColor: voiceAssistantPalette.shadowVoice,
    shadowOpacity: 1,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 5,
  },
  voiceTranscriptShadow: {
    shadowColor: voiceAssistantPalette.shadowVoice,
    shadowOpacity: 0.9,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  listScrollContent: {
    paddingBottom: 18,
  },
  conversationScrollContent: {
    paddingBottom: 18,
  },
  quickChipScrollContent: {
    paddingRight: 16,
  },
});
