const MESSAGE_TYPE_NAME_MAP: Record<number, string> = {
  3003: 'MESSAGE_TYPE_DIALOG_SESSION_STARTED_LEGACY',
  3007: 'MESSAGE_TYPE_DIALOG_TTS_SENTENCE_END',
  3008: 'MESSAGE_TYPE_DIALOG_TTS_SENTENCE_START',
  3009: 'MESSAGE_TYPE_DIALOG_USAGE_RESPONSE',
  3010: 'MESSAGE_TYPE_DIALOG_TTS_RESPONSE',
  3011: 'MESSAGE_TYPE_DIALOG_TTS_ENDED',
  3012: 'MESSAGE_TYPE_DIALOG_ASR_INFO',
  3013: 'MESSAGE_TYPE_DIALOG_ASR_RESPONSE',
  3014: 'MESSAGE_TYPE_DIALOG_ASR_ENDED',
  3015: 'MESSAGE_TYPE_DIALOG_CHAT_RESPONSE',
  3016: 'MESSAGE_TYPE_DIALOG_CHAT_ENDED',
  3018: 'MESSAGE_TYPE_DIALOG_PLAYER_AUDIO',
  3019: 'MESSAGE_TYPE_PLAYER_START_PLAY_AUDIO',
  3020: 'MESSAGE_TYPE_PLAYER_FINISH_PLAY_AUDIO',
  350: 'MESSAGE_TYPE_EVENT_TTS_SENTENCE_START_LEGACY',
  352: 'MESSAGE_TYPE_EVENT_TTS_RESPONSE_LEGACY',
  359: 'MESSAGE_TYPE_EVENT_TTS_ENDED_LEGACY',
  550: 'MESSAGE_TYPE_EVENT_CHAT_RESPONSE_LEGACY',
  559: 'MESSAGE_TYPE_EVENT_CHAT_ENDED_LEGACY',
};

export function resolveDialogNativeMessageTypeName(input?: string | number | null): string | undefined {
  if (typeof input === 'number' && Number.isFinite(input)) {
    return MESSAGE_TYPE_NAME_MAP[input] ?? `UNKNOWN_MESSAGE_TYPE_${input}`;
  }
  if (typeof input === 'string' && input.trim()) {
    const parsed = Number(input);
    if (Number.isFinite(parsed)) {
      return MESSAGE_TYPE_NAME_MAP[parsed] ?? `UNKNOWN_MESSAGE_TYPE_${parsed}`;
    }
    return input;
  }
  return undefined;
}

